from pathlib import Path

APP_NAME = "Data Bakery by Hassan Absar"
POWERED_BY = "Powered by STT Solutions"
SHORT_NAME = "Data Bakery"
TARGET_URL = "databakerybyhassanabsarsttsolutions.streamlit.app"

ASSETS_DIR = Path(__file__).resolve().parent / "assets"
HASSAN_PORTRAIT_PATH = ASSETS_DIR / "HassanAbsar.png"
HASSAN_AVATAR_PATH = ASSETS_DIR / "HassanAbsar.png"
STT_BANNER_PATH = ASSETS_DIR / "stt_solutions_banner.jpg"

ROW_MIN = 500_000
ROW_MAX = 550_000
ROW_DEFAULT = 500_000
COLUMN_MIN = 5
COLUMN_MAX = 25
COLUMN_DEFAULT = 15
CANDIDATE_COLUMN_COUNT = 25
PREVIEW_ROWS = 100
CHUNK_SIZE = 50_000

OUTPUT_ROOT_NAME = "Data_Bakery_Output"
DATASET_CSV_NAME = "dataset.csv"

ALLOWED_PACKAGE_EXTENSIONS = {".csv", ".pdf"}

TEMP_ROOT = Path("/tmp/data_bakery_sessions")
TEMP_ROOT.mkdir(parents=True, exist_ok=True)

FOOTER_TEXT = "Generated by Data Bakery by Hassan Absar | STT Solutions AI & Data Learning Systems"
SYNTHETIC_DISCLAIMER = (
    "This dataset is fully synthetic and generated only for learning, demonstration, "
    "Power BI practice, data cleaning, and visualization exercises. It does not contain real personal, "
    "banking, patient, commercial, or confidential records."
)

LEARNING_OBJECTIVES = [
    "Meaningful Data Cleaning",
    "Meaningful Data Visualization",
    "Data Cleaning + Visualization",
    "KPI Dashboard Building",
    "Time-Series Analysis",
    "Geospatial Analysis",
    "Customer / User Segmentation",
    "Financial Analysis",
    "Risk Scoring / Classification",
    "Survey / Response Analysis",
    "Operational Performance Analysis",
    "Relational Data Modeling",
    "Beginner Power Query Practice",
    "Advanced Power Query Practice",
    "Executive Dashboard Practice",
]

DATA_TYPES = [
    "Text",
    "Number",
    "Decimal",
    "Accounting",
    "Percent",
    "Binary",
    "Date",
    "DateTime",
    "Categorical",
    "ID",
    "Geographic",
]

DIRT_TYPES = [
    "Missing values and blank cells",
    "Leading and trailing white spaces",
    "Mixed letter casing",
    "Duplicate records",
    "Typographical errors and misspellings",
    "Inconsistent date formats",
    "Invalid or impossible numeric values",
    "Special characters and emojis in text fields",
    "Inconsistent categorical labels",
    "Delimiter collisions in raw text",
    "Trailing or leading zeros treated inconsistently",
    "Hardcoded placeholders or error codes",
    "Out-of-bounds geographic coordinates",
    "Hidden non-printing control characters",
    "Skewed timezones across timestamps",
]

DIRT_INTENSITIES = {
    "Light": 0.025,
    "Medium": 0.075,
    "Heavy": 0.18,
    "Extreme": 0.32,
}

TYPE_COMPATIBLE_DIRT = {
    "Text": [
        "Missing values and blank cells",
        "Leading and trailing white spaces",
        "Mixed letter casing",
        "Typographical errors and misspellings",
        "Special characters and emojis in text fields",
        "Delimiter collisions in raw text",
        "Hardcoded placeholders or error codes",
        "Hidden non-printing control characters",
    ],
    "Categorical": [
        "Missing values and blank cells",
        "Leading and trailing white spaces",
        "Mixed letter casing",
        "Typographical errors and misspellings",
        "Inconsistent categorical labels",
        "Special characters and emojis in text fields",
        "Hardcoded placeholders or error codes",
        "Hidden non-printing control characters",
    ],
    "ID": [
        "Missing values and blank cells",
        "Duplicate records",
        "Trailing or leading zeros treated inconsistently",
        "Hardcoded placeholders or error codes",
        "Hidden non-printing control characters",
    ],
    "Number": [
        "Missing values and blank cells",
        "Invalid or impossible numeric values",
        "Hardcoded placeholders or error codes",
    ],
    "Decimal": [
        "Missing values and blank cells",
        "Invalid or impossible numeric values",
        "Hardcoded placeholders or error codes",
    ],
    "Accounting": [
        "Missing values and blank cells",
        "Invalid or impossible numeric values",
        "Hardcoded placeholders or error codes",
    ],
    "Percent": [
        "Missing values and blank cells",
        "Invalid or impossible numeric values",
        "Hardcoded placeholders or error codes",
    ],
    "Binary": [
        "Missing values and blank cells",
        "Hardcoded placeholders or error codes",
    ],
    "Date": [
        "Missing values and blank cells",
        "Inconsistent date formats",
        "Hardcoded placeholders or error codes",
    ],
    "DateTime": [
        "Missing values and blank cells",
        "Inconsistent date formats",
        "Hardcoded placeholders or error codes",
        "Skewed timezones across timestamps",
    ],
    "Geographic": [
        "Missing values and blank cells",
        "Invalid or impossible numeric values",
        "Out-of-bounds geographic coordinates",
        "Hardcoded placeholders or error codes",
    ],
}
